
name: build pull request
on:
  pull_request:
    branches:
      - master

jobs:
  build-pull-request:
    runs-on: ubuntu-latest
    steps:

    - name: 🛎️ checkout
      uses: actions/checkout@v2

    - name: 🔧 set up node
      uses: actions/setup-node@v2
      with:
        node-version: '17'

    - name: 📦 npm install and build
      shell: bash
      run: npm ci && npm run build
